name = "KmerAnalysisMakie"
uuid = "da464f59-a6cf-4c57-92f9-0556c3abcc34"
authors = ["Ben J. Ward <benjward@protonmail.com>"]
version = "0.1.0"

[deps]
AbstractPlotting = "537997a7-5e4e-5d89-9595-2241ea00577e"
KmerAnalysis = "a20136b7-8e32-4c10-91d3-7060c0bd8ec7"

[compat]
AbstractPlotting = "0.11"
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]